application:
  name: "datagrid"
  version: "1.4.0"
  environment: "development"
  log_level: "debug"
  author: "Gabor Nemet"

server:
  port: "8085"

database:
  - name: "local"
    host: "${DB_HOST}"
    port: "${DB_PORT}"
    user: "${DB_USER}"
    password: "${DB_PASSWORD}"
    database: "${DB_NAME}"
    schema: "${DB_SCHEMA}"
    default: true

catalog:
  path: "catalog/personnel.json"
